export {
  canonicalizeBookTitle,
  canonicalizeContributorName,
  canonicalizeContributorNames,
  classifyMediaKind,
  createIdentifierMap,
  getFileExtension,
  hashFileContents,
  hashFileAsset,
  isFileChanged,
  matchFileAssetToEdition,
  normalizeAudiobookMetadata,
  normalizeBookMetadata,
  normalizeOpfMetadata,
  normalizeRelativePath,
  normalizeRootPath,
  parseAudiobookMetadataJson,
  parseAudioId3Tags,
  parseEpubMetadata,
  parseFileAssetMetadata,
  parseOpfSidecar,
  scanLibraryRoot,
  walkRegularFiles,
  createIngestServices,
} from "./services";

export type {
  HashFileAssetInput,
  HashFileAssetResult,
  IngestDb,
  IngestDependencies,
  MatchFileAssetToEditionInput,
  MatchFileAssetToEditionResult,
  NormalizedBookMetadata,
  ParsedAudiobookMetadataJsonRaw,
  ParsedAudioId3TagsRaw,
  ParsedEpubMetadataRaw,
  ParsedOpfMetadataRaw,
  ParseFileAssetMetadataInput,
  ParseFileAssetMetadataResult,
  ScanLibraryRootInput,
  ScanLibraryRootResult,
  ScanProgressData,
} from "./services";

export { PARTIAL_HASH_BYTES } from "./hashing";
export { SCAN_PROGRESS_INTERVAL } from "./services";

export const INGEST_PUBLIC_API = [
  "classifyMediaKind",
  "createIdentifierMap",
  "createIngestServices",
  "canonicalizeBookTitle",
  "canonicalizeContributorName",
  "canonicalizeContributorNames",
  "getFileExtension",
  "hashFileAsset",
  "hashFileContents",
  "isFileChanged",
  "matchFileAssetToEdition",
  "normalizeAudiobookMetadata",
  "normalizeBookMetadata",
  "normalizeOpfMetadata",
  "normalizeRelativePath",
  "normalizeRootPath",
  "parseAudiobookMetadataJson",
  "parseAudioId3Tags",
  "parseEpubMetadata",
  "parseFileAssetMetadata",
  "parseOpfSidecar",
  "scanLibraryRoot",
  "walkRegularFiles",
] as const;
