packages:
  - apps/*
  - packages/*
  - workers/*

onlyBuiltDependencies:
  - /
  - '@'
  - '@prisma/engines'
  - a
  - e
  - esbuild
  - g
  - i
  - m
  - msgpackr-extract
  - msw
  - n
  - p
  - prisma
  - r
  - s
  - sharp
