/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedShelvesRouteImport } from './routes/_authenticated/shelves'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'
import { Route as AuthenticatedMatchSuggestionsRouteImport } from './routes/_authenticated/match-suggestions'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDuplicatesRouteImport } from './routes/_authenticated/duplicates'
import { Route as AuthenticatedAuthorsRouteImport } from './routes/_authenticated/authors'
import { Route as AuthenticatedShelvesIndexRouteImport } from './routes/_authenticated/shelves.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSeriesIndexRouteImport } from './routes/_authenticated/series.index'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library.index'
import { Route as AuthenticatedAuthorsIndexRouteImport } from './routes/_authenticated/authors.index'
import { Route as AuthenticatedShelvesShelfIdRouteImport } from './routes/_authenticated/shelves.$shelfId'
import { Route as AuthenticatedSettingsMissingFilesRouteImport } from './routes/_authenticated/settings/missing-files'
import { Route as AuthenticatedSettingsLibrariesRouteImport } from './routes/_authenticated/settings/libraries'
import { Route as AuthenticatedSettingsJobsRouteImport } from './routes/_authenticated/settings/jobs'
import { Route as AuthenticatedSeriesSeriesIdRouteImport } from './routes/_authenticated/series.$seriesId'
import { Route as AuthenticatedLibraryWorkIdRouteImport } from './routes/_authenticated/library.$workId'
import { Route as AuthenticatedAuthorsAuthorIdRouteImport } from './routes/_authenticated/authors.$authorId'
import { Route as AuthenticatedSettingsJobsIndexRouteImport } from './routes/_authenticated/settings/jobs.index'
import { Route as AuthenticatedSettingsLibraryIssuesLibraryRootIdRouteImport } from './routes/_authenticated/settings/library-issues.$libraryRootId'
import { Route as AuthenticatedSettingsJobsJobIdRouteImport } from './routes/_authenticated/settings/jobs.$jobId'

const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShelvesRoute = AuthenticatedShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchSuggestionsRoute =
  AuthenticatedMatchSuggestionsRouteImport.update({
    id: '/match-suggestions',
    path: '/match-suggestions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDuplicatesRoute = AuthenticatedDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorsRoute = AuthenticatedAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShelvesIndexRoute =
  AuthenticatedShelvesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShelvesRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSeriesIndexRoute =
  AuthenticatedSeriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeriesRoute,
  } as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedAuthorsIndexRoute =
  AuthenticatedAuthorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuthorsRoute,
  } as any)
const AuthenticatedShelvesShelfIdRoute =
  AuthenticatedShelvesShelfIdRouteImport.update({
    id: '/$shelfId',
    path: '/$shelfId',
    getParentRoute: () => AuthenticatedShelvesRoute,
  } as any)
const AuthenticatedSettingsMissingFilesRoute =
  AuthenticatedSettingsMissingFilesRouteImport.update({
    id: '/missing-files',
    path: '/missing-files',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLibrariesRoute =
  AuthenticatedSettingsLibrariesRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsJobsRoute =
  AuthenticatedSettingsJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSeriesSeriesIdRoute =
  AuthenticatedSeriesSeriesIdRouteImport.update({
    id: '/$seriesId',
    path: '/$seriesId',
    getParentRoute: () => AuthenticatedSeriesRoute,
  } as any)
const AuthenticatedLibraryWorkIdRoute =
  AuthenticatedLibraryWorkIdRouteImport.update({
    id: '/$workId',
    path: '/$workId',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedAuthorsAuthorIdRoute =
  AuthenticatedAuthorsAuthorIdRouteImport.update({
    id: '/$authorId',
    path: '/$authorId',
    getParentRoute: () => AuthenticatedAuthorsRoute,
  } as any)
const AuthenticatedSettingsJobsIndexRoute =
  AuthenticatedSettingsJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsJobsRoute,
  } as any)
const AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute =
  AuthenticatedSettingsLibraryIssuesLibraryRootIdRouteImport.update({
    id: '/library-issues/$libraryRootId',
    path: '/library-issues/$libraryRootId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsJobsJobIdRoute =
  AuthenticatedSettingsJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedSettingsJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/logged-out': typeof LoggedOutRoute
  '/authors': typeof AuthenticatedAuthorsRouteWithChildren
  '/duplicates': typeof AuthenticatedDuplicatesRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/match-suggestions': typeof AuthenticatedMatchSuggestionsRoute
  '/series': typeof AuthenticatedSeriesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shelves': typeof AuthenticatedShelvesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/authors/$authorId': typeof AuthenticatedAuthorsAuthorIdRoute
  '/library/$workId': typeof AuthenticatedLibraryWorkIdRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsRouteWithChildren
  '/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/settings/missing-files': typeof AuthenticatedSettingsMissingFilesRoute
  '/shelves/$shelfId': typeof AuthenticatedShelvesShelfIdRoute
  '/authors/': typeof AuthenticatedAuthorsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/series/': typeof AuthenticatedSeriesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shelves/': typeof AuthenticatedShelvesIndexRoute
  '/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
  '/settings/library-issues/$libraryRootId': typeof AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute
  '/settings/jobs/': typeof AuthenticatedSettingsJobsIndexRoute
}
export interface FileRoutesByTo {
  '/logged-out': typeof LoggedOutRoute
  '/duplicates': typeof AuthenticatedDuplicatesRoute
  '/match-suggestions': typeof AuthenticatedMatchSuggestionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/authors/$authorId': typeof AuthenticatedAuthorsAuthorIdRoute
  '/library/$workId': typeof AuthenticatedLibraryWorkIdRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/settings/missing-files': typeof AuthenticatedSettingsMissingFilesRoute
  '/shelves/$shelfId': typeof AuthenticatedShelvesShelfIdRoute
  '/authors': typeof AuthenticatedAuthorsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/series': typeof AuthenticatedSeriesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shelves': typeof AuthenticatedShelvesIndexRoute
  '/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
  '/settings/library-issues/$libraryRootId': typeof AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logged-out': typeof LoggedOutRoute
  '/_authenticated/authors': typeof AuthenticatedAuthorsRouteWithChildren
  '/_authenticated/duplicates': typeof AuthenticatedDuplicatesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/match-suggestions': typeof AuthenticatedMatchSuggestionsRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/shelves': typeof AuthenticatedShelvesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/authors/$authorId': typeof AuthenticatedAuthorsAuthorIdRoute
  '/_authenticated/library/$workId': typeof AuthenticatedLibraryWorkIdRoute
  '/_authenticated/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/_authenticated/settings/jobs': typeof AuthenticatedSettingsJobsRouteWithChildren
  '/_authenticated/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/_authenticated/settings/missing-files': typeof AuthenticatedSettingsMissingFilesRoute
  '/_authenticated/shelves/$shelfId': typeof AuthenticatedShelvesShelfIdRoute
  '/_authenticated/authors/': typeof AuthenticatedAuthorsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/series/': typeof AuthenticatedSeriesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shelves/': typeof AuthenticatedShelvesIndexRoute
  '/_authenticated/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
  '/_authenticated/settings/library-issues/$libraryRootId': typeof AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute
  '/_authenticated/settings/jobs/': typeof AuthenticatedSettingsJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logged-out'
    | '/authors'
    | '/duplicates'
    | '/library'
    | '/match-suggestions'
    | '/series'
    | '/settings'
    | '/shelves'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/authors/$authorId'
    | '/library/$workId'
    | '/series/$seriesId'
    | '/settings/jobs'
    | '/settings/libraries'
    | '/settings/missing-files'
    | '/shelves/$shelfId'
    | '/authors/'
    | '/library/'
    | '/series/'
    | '/settings/'
    | '/shelves/'
    | '/settings/jobs/$jobId'
    | '/settings/library-issues/$libraryRootId'
    | '/settings/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logged-out'
    | '/duplicates'
    | '/match-suggestions'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/'
    | '/authors/$authorId'
    | '/library/$workId'
    | '/series/$seriesId'
    | '/settings/libraries'
    | '/settings/missing-files'
    | '/shelves/$shelfId'
    | '/authors'
    | '/library'
    | '/series'
    | '/settings'
    | '/shelves'
    | '/settings/jobs/$jobId'
    | '/settings/library-issues/$libraryRootId'
    | '/settings/jobs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/logged-out'
    | '/_authenticated/authors'
    | '/_authenticated/duplicates'
    | '/_authenticated/library'
    | '/_authenticated/match-suggestions'
    | '/_authenticated/series'
    | '/_authenticated/settings'
    | '/_authenticated/shelves'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/_authenticated/'
    | '/_authenticated/authors/$authorId'
    | '/_authenticated/library/$workId'
    | '/_authenticated/series/$seriesId'
    | '/_authenticated/settings/jobs'
    | '/_authenticated/settings/libraries'
    | '/_authenticated/settings/missing-files'
    | '/_authenticated/shelves/$shelfId'
    | '/_authenticated/authors/'
    | '/_authenticated/library/'
    | '/_authenticated/series/'
    | '/_authenticated/settings/'
    | '/_authenticated/shelves/'
    | '/_authenticated/settings/jobs/$jobId'
    | '/_authenticated/settings/library-issues/$libraryRootId'
    | '/_authenticated/settings/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoggedOutRoute: typeof LoggedOutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shelves': {
      id: '/_authenticated/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof AuthenticatedShelvesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/match-suggestions': {
      id: '/_authenticated/match-suggestions'
      path: '/match-suggestions'
      fullPath: '/match-suggestions'
      preLoaderRoute: typeof AuthenticatedMatchSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duplicates': {
      id: '/_authenticated/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AuthenticatedDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authors': {
      id: '/_authenticated/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthenticatedAuthorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shelves/': {
      id: '/_authenticated/shelves/'
      path: '/'
      fullPath: '/shelves/'
      preLoaderRoute: typeof AuthenticatedShelvesIndexRouteImport
      parentRoute: typeof AuthenticatedShelvesRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/series/': {
      id: '/_authenticated/series/'
      path: '/'
      fullPath: '/series/'
      preLoaderRoute: typeof AuthenticatedSeriesIndexRouteImport
      parentRoute: typeof AuthenticatedSeriesRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/authors/': {
      id: '/_authenticated/authors/'
      path: '/'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthenticatedAuthorsIndexRouteImport
      parentRoute: typeof AuthenticatedAuthorsRoute
    }
    '/_authenticated/shelves/$shelfId': {
      id: '/_authenticated/shelves/$shelfId'
      path: '/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof AuthenticatedShelvesShelfIdRouteImport
      parentRoute: typeof AuthenticatedShelvesRoute
    }
    '/_authenticated/settings/missing-files': {
      id: '/_authenticated/settings/missing-files'
      path: '/missing-files'
      fullPath: '/settings/missing-files'
      preLoaderRoute: typeof AuthenticatedSettingsMissingFilesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/libraries': {
      id: '/_authenticated/settings/libraries'
      path: '/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof AuthenticatedSettingsLibrariesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/jobs': {
      id: '/_authenticated/settings/jobs'
      path: '/jobs'
      fullPath: '/settings/jobs'
      preLoaderRoute: typeof AuthenticatedSettingsJobsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/series/$seriesId': {
      id: '/_authenticated/series/$seriesId'
      path: '/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AuthenticatedSeriesSeriesIdRouteImport
      parentRoute: typeof AuthenticatedSeriesRoute
    }
    '/_authenticated/library/$workId': {
      id: '/_authenticated/library/$workId'
      path: '/$workId'
      fullPath: '/library/$workId'
      preLoaderRoute: typeof AuthenticatedLibraryWorkIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/authors/$authorId': {
      id: '/_authenticated/authors/$authorId'
      path: '/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthenticatedAuthorsAuthorIdRouteImport
      parentRoute: typeof AuthenticatedAuthorsRoute
    }
    '/_authenticated/settings/jobs/': {
      id: '/_authenticated/settings/jobs/'
      path: '/'
      fullPath: '/settings/jobs/'
      preLoaderRoute: typeof AuthenticatedSettingsJobsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsJobsRoute
    }
    '/_authenticated/settings/library-issues/$libraryRootId': {
      id: '/_authenticated/settings/library-issues/$libraryRootId'
      path: '/library-issues/$libraryRootId'
      fullPath: '/settings/library-issues/$libraryRootId'
      preLoaderRoute: typeof AuthenticatedSettingsLibraryIssuesLibraryRootIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/jobs/$jobId': {
      id: '/_authenticated/settings/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/settings/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedSettingsJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedSettingsJobsRoute
    }
  }
}

interface AuthenticatedAuthorsRouteChildren {
  AuthenticatedAuthorsAuthorIdRoute: typeof AuthenticatedAuthorsAuthorIdRoute
  AuthenticatedAuthorsIndexRoute: typeof AuthenticatedAuthorsIndexRoute
}

const AuthenticatedAuthorsRouteChildren: AuthenticatedAuthorsRouteChildren = {
  AuthenticatedAuthorsAuthorIdRoute: AuthenticatedAuthorsAuthorIdRoute,
  AuthenticatedAuthorsIndexRoute: AuthenticatedAuthorsIndexRoute,
}

const AuthenticatedAuthorsRouteWithChildren =
  AuthenticatedAuthorsRoute._addFileChildren(AuthenticatedAuthorsRouteChildren)

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryWorkIdRoute: typeof AuthenticatedLibraryWorkIdRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryWorkIdRoute: AuthenticatedLibraryWorkIdRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedSeriesRouteChildren {
  AuthenticatedSeriesSeriesIdRoute: typeof AuthenticatedSeriesSeriesIdRoute
  AuthenticatedSeriesIndexRoute: typeof AuthenticatedSeriesIndexRoute
}

const AuthenticatedSeriesRouteChildren: AuthenticatedSeriesRouteChildren = {
  AuthenticatedSeriesSeriesIdRoute: AuthenticatedSeriesSeriesIdRoute,
  AuthenticatedSeriesIndexRoute: AuthenticatedSeriesIndexRoute,
}

const AuthenticatedSeriesRouteWithChildren =
  AuthenticatedSeriesRoute._addFileChildren(AuthenticatedSeriesRouteChildren)

interface AuthenticatedSettingsJobsRouteChildren {
  AuthenticatedSettingsJobsJobIdRoute: typeof AuthenticatedSettingsJobsJobIdRoute
  AuthenticatedSettingsJobsIndexRoute: typeof AuthenticatedSettingsJobsIndexRoute
}

const AuthenticatedSettingsJobsRouteChildren: AuthenticatedSettingsJobsRouteChildren =
  {
    AuthenticatedSettingsJobsJobIdRoute: AuthenticatedSettingsJobsJobIdRoute,
    AuthenticatedSettingsJobsIndexRoute: AuthenticatedSettingsJobsIndexRoute,
  }

const AuthenticatedSettingsJobsRouteWithChildren =
  AuthenticatedSettingsJobsRoute._addFileChildren(
    AuthenticatedSettingsJobsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsJobsRoute: typeof AuthenticatedSettingsJobsRouteWithChildren
  AuthenticatedSettingsLibrariesRoute: typeof AuthenticatedSettingsLibrariesRoute
  AuthenticatedSettingsMissingFilesRoute: typeof AuthenticatedSettingsMissingFilesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute: typeof AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsJobsRoute: AuthenticatedSettingsJobsRouteWithChildren,
  AuthenticatedSettingsLibrariesRoute: AuthenticatedSettingsLibrariesRoute,
  AuthenticatedSettingsMissingFilesRoute:
    AuthenticatedSettingsMissingFilesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute:
    AuthenticatedSettingsLibraryIssuesLibraryRootIdRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedShelvesRouteChildren {
  AuthenticatedShelvesShelfIdRoute: typeof AuthenticatedShelvesShelfIdRoute
  AuthenticatedShelvesIndexRoute: typeof AuthenticatedShelvesIndexRoute
}

const AuthenticatedShelvesRouteChildren: AuthenticatedShelvesRouteChildren = {
  AuthenticatedShelvesShelfIdRoute: AuthenticatedShelvesShelfIdRoute,
  AuthenticatedShelvesIndexRoute: AuthenticatedShelvesIndexRoute,
}

const AuthenticatedShelvesRouteWithChildren =
  AuthenticatedShelvesRoute._addFileChildren(AuthenticatedShelvesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuthorsRoute: typeof AuthenticatedAuthorsRouteWithChildren
  AuthenticatedDuplicatesRoute: typeof AuthenticatedDuplicatesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedMatchSuggestionsRoute: typeof AuthenticatedMatchSuggestionsRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedShelvesRoute: typeof AuthenticatedShelvesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthorsRoute: AuthenticatedAuthorsRouteWithChildren,
  AuthenticatedDuplicatesRoute: AuthenticatedDuplicatesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedMatchSuggestionsRoute: AuthenticatedMatchSuggestionsRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedShelvesRoute: AuthenticatedShelvesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoggedOutRoute: LoggedOutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
