/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AudioLinksRouteImport } from './routes/audio-links'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksWorkIdRouteImport } from './routes/works.$workId'
import { Route as DuplicatesCandidateIdRouteImport } from './routes/duplicates.$candidateId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AudioLinksLinkIdRouteImport } from './routes/audio-links.$linkId'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiProgressModeRouteImport } from './routes/api/progress/mode'
import { Route as ApiProgressWorksWorkIdRouteImport } from './routes/api/progress/works/$workId'
import { Route as ApiProgressWorksWorkIdModeRouteImport } from './routes/api/progress/works/$workId/mode'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioLinksRoute = AudioLinksRouteImport.update({
  id: '/audio-links',
  path: '/audio-links',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesCandidateIdRoute = DuplicatesCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => DuplicatesRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioLinksLinkIdRoute = AudioLinksLinkIdRouteImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => AudioLinksRoute,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressModeRoute = ApiProgressModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => ApiProgressRoute,
} as any)
const ApiProgressWorksWorkIdRoute = ApiProgressWorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => ApiProgressRoute,
} as any)
const ApiProgressWorksWorkIdModeRoute =
  ApiProgressWorksWorkIdModeRouteImport.update({
    id: '/mode',
    path: '/mode',
    getParentRoute: () => ApiProgressWorksWorkIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-links': typeof AudioLinksRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/duplicates': typeof DuplicatesRouteWithChildren
  '/library': typeof LibraryRoute
  '/logged-out': typeof LoggedOutRoute
  '/settings': typeof SettingsRoute
  '/api/progress': typeof ApiProgressRouteWithChildren
  '/audio-links/$linkId': typeof AudioLinksLinkIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/duplicates/$candidateId': typeof DuplicatesCandidateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/api/progress/mode': typeof ApiProgressModeRoute
  '/api/progress/works/$workId': typeof ApiProgressWorksWorkIdRouteWithChildren
  '/api/progress/works/$workId/mode': typeof ApiProgressWorksWorkIdModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-links': typeof AudioLinksRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/duplicates': typeof DuplicatesRouteWithChildren
  '/library': typeof LibraryRoute
  '/logged-out': typeof LoggedOutRoute
  '/settings': typeof SettingsRoute
  '/api/progress': typeof ApiProgressRouteWithChildren
  '/audio-links/$linkId': typeof AudioLinksLinkIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/duplicates/$candidateId': typeof DuplicatesCandidateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/api/progress/mode': typeof ApiProgressModeRoute
  '/api/progress/works/$workId': typeof ApiProgressWorksWorkIdRouteWithChildren
  '/api/progress/works/$workId/mode': typeof ApiProgressWorksWorkIdModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-links': typeof AudioLinksRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/duplicates': typeof DuplicatesRouteWithChildren
  '/library': typeof LibraryRoute
  '/logged-out': typeof LoggedOutRoute
  '/settings': typeof SettingsRoute
  '/api/progress': typeof ApiProgressRouteWithChildren
  '/audio-links/$linkId': typeof AudioLinksLinkIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/duplicates/$candidateId': typeof DuplicatesCandidateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/api/progress/mode': typeof ApiProgressModeRoute
  '/api/progress/works/$workId': typeof ApiProgressWorksWorkIdRouteWithChildren
  '/api/progress/works/$workId/mode': typeof ApiProgressWorksWorkIdModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-links'
    | '/collections'
    | '/duplicates'
    | '/library'
    | '/logged-out'
    | '/settings'
    | '/api/progress'
    | '/audio-links/$linkId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/collections/$collectionId'
    | '/duplicates/$candidateId'
    | '/works/$workId'
    | '/api/progress/mode'
    | '/api/progress/works/$workId'
    | '/api/progress/works/$workId/mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-links'
    | '/collections'
    | '/duplicates'
    | '/library'
    | '/logged-out'
    | '/settings'
    | '/api/progress'
    | '/audio-links/$linkId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/collections/$collectionId'
    | '/duplicates/$candidateId'
    | '/works/$workId'
    | '/api/progress/mode'
    | '/api/progress/works/$workId'
    | '/api/progress/works/$workId/mode'
  id:
    | '__root__'
    | '/'
    | '/audio-links'
    | '/collections'
    | '/duplicates'
    | '/library'
    | '/logged-out'
    | '/settings'
    | '/api/progress'
    | '/audio-links/$linkId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/collections/$collectionId'
    | '/duplicates/$candidateId'
    | '/works/$workId'
    | '/api/progress/mode'
    | '/api/progress/works/$workId'
    | '/api/progress/works/$workId/mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioLinksRoute: typeof AudioLinksRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DuplicatesRoute: typeof DuplicatesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoggedOutRoute: typeof LoggedOutRoute
  SettingsRoute: typeof SettingsRoute
  ApiProgressRoute: typeof ApiProgressRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-links': {
      id: '/audio-links'
      path: '/audio-links'
      fullPath: '/audio-links'
      preLoaderRoute: typeof AudioLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates/$candidateId': {
      id: '/duplicates/$candidateId'
      path: '/$candidateId'
      fullPath: '/duplicates/$candidateId'
      preLoaderRoute: typeof DuplicatesCandidateIdRouteImport
      parentRoute: typeof DuplicatesRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-links/$linkId': {
      id: '/audio-links/$linkId'
      path: '/$linkId'
      fullPath: '/audio-links/$linkId'
      preLoaderRoute: typeof AudioLinksLinkIdRouteImport
      parentRoute: typeof AudioLinksRoute
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/mode': {
      id: '/api/progress/mode'
      path: '/mode'
      fullPath: '/api/progress/mode'
      preLoaderRoute: typeof ApiProgressModeRouteImport
      parentRoute: typeof ApiProgressRoute
    }
    '/api/progress/works/$workId': {
      id: '/api/progress/works/$workId'
      path: '/works/$workId'
      fullPath: '/api/progress/works/$workId'
      preLoaderRoute: typeof ApiProgressWorksWorkIdRouteImport
      parentRoute: typeof ApiProgressRoute
    }
    '/api/progress/works/$workId/mode': {
      id: '/api/progress/works/$workId/mode'
      path: '/mode'
      fullPath: '/api/progress/works/$workId/mode'
      preLoaderRoute: typeof ApiProgressWorksWorkIdModeRouteImport
      parentRoute: typeof ApiProgressWorksWorkIdRoute
    }
  }
}

interface AudioLinksRouteChildren {
  AudioLinksLinkIdRoute: typeof AudioLinksLinkIdRoute
}

const AudioLinksRouteChildren: AudioLinksRouteChildren = {
  AudioLinksLinkIdRoute: AudioLinksLinkIdRoute,
}

const AudioLinksRouteWithChildren = AudioLinksRoute._addFileChildren(
  AudioLinksRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface DuplicatesRouteChildren {
  DuplicatesCandidateIdRoute: typeof DuplicatesCandidateIdRoute
}

const DuplicatesRouteChildren: DuplicatesRouteChildren = {
  DuplicatesCandidateIdRoute: DuplicatesCandidateIdRoute,
}

const DuplicatesRouteWithChildren = DuplicatesRoute._addFileChildren(
  DuplicatesRouteChildren,
)

interface ApiProgressWorksWorkIdRouteChildren {
  ApiProgressWorksWorkIdModeRoute: typeof ApiProgressWorksWorkIdModeRoute
}

const ApiProgressWorksWorkIdRouteChildren: ApiProgressWorksWorkIdRouteChildren =
  {
    ApiProgressWorksWorkIdModeRoute: ApiProgressWorksWorkIdModeRoute,
  }

const ApiProgressWorksWorkIdRouteWithChildren =
  ApiProgressWorksWorkIdRoute._addFileChildren(
    ApiProgressWorksWorkIdRouteChildren,
  )

interface ApiProgressRouteChildren {
  ApiProgressModeRoute: typeof ApiProgressModeRoute
  ApiProgressWorksWorkIdRoute: typeof ApiProgressWorksWorkIdRouteWithChildren
}

const ApiProgressRouteChildren: ApiProgressRouteChildren = {
  ApiProgressModeRoute: ApiProgressModeRoute,
  ApiProgressWorksWorkIdRoute: ApiProgressWorksWorkIdRouteWithChildren,
}

const ApiProgressRouteWithChildren = ApiProgressRoute._addFileChildren(
  ApiProgressRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioLinksRoute: AudioLinksRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  DuplicatesRoute: DuplicatesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoggedOutRoute: LoggedOutRoute,
  SettingsRoute: SettingsRoute,
  ApiProgressRoute: ApiProgressRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
