/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDuplicatesRouteImport } from './routes/_authenticated/duplicates'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedAudioLinksRouteImport } from './routes/_authenticated/audio-links'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsLibrariesRouteImport } from './routes/_authenticated/settings/libraries'
import { Route as AuthenticatedSettingsJobsRouteImport } from './routes/_authenticated/settings/jobs'
import { Route as AuthenticatedSettingsJobsJobIdRouteImport } from './routes/_authenticated/settings/jobs.$jobId'

const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDuplicatesRoute = AuthenticatedDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAudioLinksRoute = AuthenticatedAudioLinksRouteImport.update({
  id: '/audio-links',
  path: '/audio-links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLibrariesRoute =
  AuthenticatedSettingsLibrariesRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsJobsRoute =
  AuthenticatedSettingsJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsJobsJobIdRoute =
  AuthenticatedSettingsJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedSettingsJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/logged-out': typeof LoggedOutRoute
  '/audio-links': typeof AuthenticatedAudioLinksRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/duplicates': typeof AuthenticatedDuplicatesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsRouteWithChildren
  '/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/logged-out': typeof LoggedOutRoute
  '/audio-links': typeof AuthenticatedAudioLinksRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/duplicates': typeof AuthenticatedDuplicatesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsRouteWithChildren
  '/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logged-out': typeof LoggedOutRoute
  '/_authenticated/audio-links': typeof AuthenticatedAudioLinksRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/duplicates': typeof AuthenticatedDuplicatesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/jobs': typeof AuthenticatedSettingsJobsRouteWithChildren
  '/_authenticated/settings/libraries': typeof AuthenticatedSettingsLibrariesRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/jobs/$jobId': typeof AuthenticatedSettingsJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logged-out'
    | '/audio-links'
    | '/collections'
    | '/duplicates'
    | '/library'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/settings/jobs'
    | '/settings/libraries'
    | '/settings/'
    | '/settings/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logged-out'
    | '/audio-links'
    | '/collections'
    | '/duplicates'
    | '/library'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/'
    | '/settings/jobs'
    | '/settings/libraries'
    | '/settings'
    | '/settings/jobs/$jobId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/logged-out'
    | '/_authenticated/audio-links'
    | '/_authenticated/collections'
    | '/_authenticated/duplicates'
    | '/_authenticated/library'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/_authenticated/'
    | '/_authenticated/settings/jobs'
    | '/_authenticated/settings/libraries'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoggedOutRoute: typeof LoggedOutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duplicates': {
      id: '/_authenticated/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AuthenticatedDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audio-links': {
      id: '/_authenticated/audio-links'
      path: '/audio-links'
      fullPath: '/audio-links'
      preLoaderRoute: typeof AuthenticatedAudioLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/libraries': {
      id: '/_authenticated/settings/libraries'
      path: '/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof AuthenticatedSettingsLibrariesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/jobs': {
      id: '/_authenticated/settings/jobs'
      path: '/jobs'
      fullPath: '/settings/jobs'
      preLoaderRoute: typeof AuthenticatedSettingsJobsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/jobs/$jobId': {
      id: '/_authenticated/settings/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/settings/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedSettingsJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedSettingsJobsRoute
    }
  }
}

interface AuthenticatedSettingsJobsRouteChildren {
  AuthenticatedSettingsJobsJobIdRoute: typeof AuthenticatedSettingsJobsJobIdRoute
}

const AuthenticatedSettingsJobsRouteChildren: AuthenticatedSettingsJobsRouteChildren =
  {
    AuthenticatedSettingsJobsJobIdRoute: AuthenticatedSettingsJobsJobIdRoute,
  }

const AuthenticatedSettingsJobsRouteWithChildren =
  AuthenticatedSettingsJobsRoute._addFileChildren(
    AuthenticatedSettingsJobsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsJobsRoute: typeof AuthenticatedSettingsJobsRouteWithChildren
  AuthenticatedSettingsLibrariesRoute: typeof AuthenticatedSettingsLibrariesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsJobsRoute: AuthenticatedSettingsJobsRouteWithChildren,
  AuthenticatedSettingsLibrariesRoute: AuthenticatedSettingsLibrariesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAudioLinksRoute: typeof AuthenticatedAudioLinksRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDuplicatesRoute: typeof AuthenticatedDuplicatesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAudioLinksRoute: AuthenticatedAudioLinksRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDuplicatesRoute: AuthenticatedDuplicatesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoggedOutRoute: LoggedOutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
